ncurses 5.7 - patch 20100227
+ add Ada95/configure script, to use in tar-file created by
  Ada95/make-tar.sh
+ fix typo in wresize.3x (patch by Tim van der Molen).
+ modify screen-bce.XXX entries to exclude ech, since screen's color
  model does not clear with color for that feature -TD

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.482 .
+# From configure.in Revision: 1.484 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20081225.
 #
@@ -17856,6 +17856,12 @@ do
 	test ! -d $cf_dir && mkdir $cf_dir
 done
 
+# symbols that differ when compiling Ada95 by itself.
+NCURSES_SHLIB2='sh $(top_srcdir)/misc/shlib'
+
+NCURSES_COPY2='sh $(top_srcdir)/tar-copy.sh'
+
+# values to use as strings
 cat >>confdefs.h <<EOF
 #define NCURSES_PATHSEP '$PATH_SEPARATOR'
 EOF
@@ -17947,18 +17953,18 @@ fi
 ### If we're building with rpath, try to link non-standard libs that way too.
 if test "$DFT_LWR_MODEL" = "shared"; then
 
-echo "$as_me:17950: checking for updated LDFLAGS" >&5
+echo "$as_me:17956: checking for updated LDFLAGS" >&5
 echo $ECHO_N "checking for updated LDFLAGS... $ECHO_C" >&6
 if test -n "$LDFLAGS" ; then
-echo "$as_me:17953: result: maybe" >&5
+echo "$as_me:17959: result: maybe" >&5
 echo "${ECHO_T}maybe" >&6
 test -n "$verbose" && echo "	...checking LDFLAGS $LDFLAGS" 1>&6
 
-echo "${as_me-configure}:17957: testing ...checking LDFLAGS $LDFLAGS ..." 1>&5
+echo "${as_me-configure}:17963: testing ...checking LDFLAGS $LDFLAGS ..." 1>&5
 
 test -n "$verbose" && echo "	...checking EXTRA_LDFLAGS $EXTRA_LDFLAGS" 1>&6
 
-echo "${as_me-configure}:17961: testing ...checking EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
+echo "${as_me-configure}:17967: testing ...checking EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
 
 case "$EXTRA_LDFLAGS" in #(vi
 -Wl,-rpath,*) #(vi
@@ -17980,7 +17986,7 @@ if test -n "$cf_rpath_hack" ; then
 	do
 		test -n "$verbose" && echo "	Filtering $cf_rpath_src" 1>&6
 
-echo "${as_me-configure}:17983: testing Filtering $cf_rpath_src ..." 1>&5
+echo "${as_me-configure}:17989: testing Filtering $cf_rpath_src ..." 1>&5
 
 		case $cf_rpath_src in #(vi
 		-L*) #(vi
@@ -17991,7 +17997,7 @@ echo "${as_me-configure}:17983: testing Filtering $cf_rpath_src ..." 1>&5
 			fi
 			test -n "$verbose" && echo "	...Filter $cf_rpath_tmp" 1>&6
 
-echo "${as_me-configure}:17994: testing ...Filter $cf_rpath_tmp ..." 1>&5
+echo "${as_me-configure}:18000: testing ...Filter $cf_rpath_tmp ..." 1>&5
 
 			EXTRA_LDFLAGS="$cf_rpath_tmp $EXTRA_LDFLAGS"
 			;;
@@ -18001,15 +18007,15 @@ echo "${as_me-configure}:17994: testing ...Filter $cf_rpath_tmp ..." 1>&5
 	LDFLAGS=$cf_rpath_dst
 	test -n "$verbose" && echo "	...checked LDFLAGS $LDFLAGS" 1>&6
 
-echo "${as_me-configure}:18004: testing ...checked LDFLAGS $LDFLAGS ..." 1>&5
+echo "${as_me-configure}:18010: testing ...checked LDFLAGS $LDFLAGS ..." 1>&5
 
 	test -n "$verbose" && echo "	...checked EXTRA_LDFLAGS $EXTRA_LDFLAGS" 1>&6
 
-echo "${as_me-configure}:18008: testing ...checked EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
+echo "${as_me-configure}:18014: testing ...checked EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
 
 fi
 else
-echo "$as_me:18012: result: no" >&5
+echo "$as_me:18018: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -18129,7 +18135,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:18132: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:18138: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -18305,7 +18311,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:18308: error: ambiguous option: $1
+    { { echo "$as_me:18314: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -18324,7 +18330,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:18327: error: unrecognized option: $1
+  -*) { { echo "$as_me:18333: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -18423,7 +18429,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "include/ncurses_cfg.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/ncurses_cfg.h:include/ncurses_cfg.hin" ;;
-  *) { { echo "$as_me:18426: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:18432: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -18698,6 +18704,8 @@ s,@TEST_ARG2@,$TEST_ARG2,;t t
 s,@TEST_DEP2@,$TEST_DEP2,;t t
 s,@ADA_SUBDIRS@,$ADA_SUBDIRS,;t t
 s,@DIRS_TO_MAKE@,$DIRS_TO_MAKE,;t t
+s,@NCURSES_SHLIB2@,$NCURSES_SHLIB2,;t t
+s,@NCURSES_COPY2@,$NCURSES_COPY2,;t t
 s,@HAVE_TCGETATTR@,$HAVE_TCGETATTR,;t t
 s,@HAVE_TERMIO_H@,$HAVE_TERMIO_H,;t t
 s,@HAVE_TERMIOS_H@,$HAVE_TERMIOS_H,;t t
@@ -18817,7 +18825,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:18820: creating $ac_file" >&5
+    { echo "$as_me:18828: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -18835,7 +18843,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:18838: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:18846: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -18848,7 +18856,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:18851: error: cannot find input file: $f" >&5
+           { { echo "$as_me:18859: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -18914,7 +18922,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:18917: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:18925: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -18925,7 +18933,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:18928: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:18936: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -18938,7 +18946,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:18941: error: cannot find input file: $f" >&5
+           { { echo "$as_me:18949: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -18996,7 +19004,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:18999: $ac_file is unchanged" >&5
+      { echo "$as_me:19007: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
