ncurses 5.7 - patch 20090815
+ correct use of terminfo capabilities for initializing soft-keys,
  broken in 20090509 merging.
+ modify wgetch() to ensure it checks SIGWINCH when it gets an error
  in non-blocking mode (patch by Clemens Ladisch).
+ use PATH_SEPARATOR symbol when substituting into run_tic.sh, to
  help with builds on non-Unix platforms such as OS/2 EMX.
+ modify scripting for misc/run_tic.sh to test configure script's
  $cross_compiling variable directly rather than comparing host/build
  compiler names (prompted by comment in GenToo #249363).
+ fix configure script option --with-database, which was coded as an
  enable-type switch.
+ build-fixes for --srcdir (report by Frederic L W Meunier).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.472 .
+# From configure.in Revision: 1.473 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20081225.
 #
@@ -5693,9 +5693,9 @@ EOF
 	echo "$as_me:5693: checking which terminfo source-file will be installed" >&5
 echo $ECHO_N "checking which terminfo source-file will be installed... $ECHO_C" >&6
 
-# Check whether --enable-database or --disable-database was given.
-if test "${enable_database+set}" = set; then
-  enableval="$enable_database"
+# Check whether --with-database or --without-database was given.
+if test "${with_database+set}" = set; then
+  withval="$with_database"
   TERMINFO_SRC=$withval
 fi;
 	echo "$as_me:5701: result: $TERMINFO_SRC" >&5
@@ -17965,6 +17965,7 @@ s,@HAVE_TCGETATTR@,$HAVE_TCGETATTR,;t t
 s,@HAVE_TERMIO_H@,$HAVE_TERMIO_H,;t t
 s,@HAVE_TERMIOS_H@,$HAVE_TERMIOS_H,;t t
 s,@MAKE_PC_FILES@,$MAKE_PC_FILES,;t t
+s,@cross_compiling@,$cross_compiling,;t t
 CEOF
 
 EOF
@@ -18079,7 +18080,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:18082: creating $ac_file" >&5
+    { echo "$as_me:18083: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -18097,7 +18098,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:18100: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:18101: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -18110,7 +18111,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:18113: error: cannot find input file: $f" >&5
+           { { echo "$as_me:18114: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -18176,7 +18177,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:18179: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:18180: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -18187,7 +18188,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:18190: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:18191: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -18200,7 +18201,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:18203: error: cannot find input file: $f" >&5
+           { { echo "$as_me:18204: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -18258,7 +18259,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:18261: $ac_file is unchanged" >&5
+      { echo "$as_me:18262: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
