ncurses 5.6 - patch 20080705
+ use NCURSES_MOUSE_MASK() in definition of BUTTON_RELEASE(), etc., to
  make those work properly with the "--enable-ext-mouse" configuration
  (cf: 20050205).
+ improve documentation of build-cc options in INSTALL.
+ work-around a bug in gcc 4.2.4 on AIX, which does not pass the
  -static/-dynamic flags properly to linker, causing test/bs to
  not link.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.434 .
+# From configure.in Revision: 1.435 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20080325.
 #
@@ -15833,8 +15833,16 @@ case $DFT_LWR_MODEL in
 normal|debug|profile)
 
 if test "$GCC" = yes ; then
-	LDFLAGS_STATIC=-static
-	LDFLAGS_SHARED=-dynamic
+	case $cf_cv_system_name in #(
+	aix[45]*) 	#( gcc 4.2.4 linkage on AIX is broken
+		LDFLAGS_STATIC=
+		LDFLAGS_SHARED=
+		;;
+    *) 	#( normally, except when broken
+        LDFLAGS_STATIC=-static
+        LDFLAGS_SHARED=-dynamic
+        ;;
+    esac
 else
 	case $cf_cv_system_name in #(
 	aix[45]*) 	#( from ld manpage
@@ -15865,12 +15873,12 @@ fi
 	;;
 esac
 
-echo "$as_me:15868: checking where we will install curses.h" >&5
+echo "$as_me:15876: checking where we will install curses.h" >&5
 echo $ECHO_N "checking where we will install curses.h... $ECHO_C" >&6
 test "$with_overwrite" = no && \
 test "x$includedir" = 'x${prefix}/include' && \
 	includedir='${prefix}/include/ncurses'${LIB_SUFFIX}
-echo "$as_me:15873: result: $includedir" >&5
+echo "$as_me:15881: result: $includedir" >&5
 echo "${ECHO_T}$includedir" >&6
 
 ### Resolve a conflict between normal and wide-curses by forcing applications
@@ -15878,7 +15886,7 @@ echo "${ECHO_T}$includedir" >&6
 if test "$with_overwrite" != no ; then
 if test "$NCURSES_LIBUTF8" = 1 ; then
 	NCURSES_LIBUTF8='defined(HAVE_LIBUTF8_H)'
-	{ echo "$as_me:15881: WARNING: Wide-character applications must define HAVE_LIBUTF8_H to include curses.h" >&5
+	{ echo "$as_me:15889: WARNING: Wide-character applications must define HAVE_LIBUTF8_H to include curses.h" >&5
 echo "$as_me: WARNING: Wide-character applications must define HAVE_LIBUTF8_H to include curses.h" >&2;}
 fi
 fi
@@ -15894,7 +15902,7 @@ EOF
 ### Construct the list of subdirectories for which we'll customize makefiles
 ### with the appropriate compile-rules.
 
-echo "$as_me:15897: checking for src modules" >&5
+echo "$as_me:15905: checking for src modules" >&5
 echo $ECHO_N "checking for src modules... $ECHO_C" >&6
 
 # dependencies and linker-arguments for test-programs
@@ -15957,7 +15965,7 @@ EOF
 		fi
 	fi
 done
-echo "$as_me:15960: result: $cf_cv_src_modules" >&5
+echo "$as_me:15968: result: $cf_cv_src_modules" >&5
 echo "${ECHO_T}$cf_cv_src_modules" >&6
 
 TEST_ARGS="-L${LIB_DIR} $TEST_ARGS"
@@ -16106,18 +16114,18 @@ fi
 ### If we're building with rpath, try to link non-standard libs that way too.
 if test "$DFT_LWR_MODEL" = "shared"; then
 
-echo "$as_me:16109: checking for updated LDFLAGS" >&5
+echo "$as_me:16117: checking for updated LDFLAGS" >&5
 echo $ECHO_N "checking for updated LDFLAGS... $ECHO_C" >&6
 if test -n "$LDFLAGS" ; then
-echo "$as_me:16112: result: maybe" >&5
+echo "$as_me:16120: result: maybe" >&5
 echo "${ECHO_T}maybe" >&6
 test -n "$verbose" && echo "	...checking LDFLAGS $LDFLAGS" 1>&6
 
-echo "${as_me-configure}:16116: testing ...checking LDFLAGS $LDFLAGS ..." 1>&5
+echo "${as_me-configure}:16124: testing ...checking LDFLAGS $LDFLAGS ..." 1>&5
 
 test -n "$verbose" && echo "	...checking EXTRA_LDFLAGS $EXTRA_LDFLAGS" 1>&6
 
-echo "${as_me-configure}:16120: testing ...checking EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
+echo "${as_me-configure}:16128: testing ...checking EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
 
 case "$EXTRA_LDFLAGS" in #(vi
 -Wl,-rpath,*) #(vi
@@ -16139,7 +16147,7 @@ if test -n "$cf_rpath_hack" ; then
     do
         test -n "$verbose" && echo "	Filtering $cf_rpath_src" 1>&6
 
-echo "${as_me-configure}:16142: testing Filtering $cf_rpath_src ..." 1>&5
+echo "${as_me-configure}:16150: testing Filtering $cf_rpath_src ..." 1>&5
 
         case $cf_rpath_src in #(vi
         -L*) #(vi
@@ -16150,7 +16158,7 @@ echo "${as_me-configure}:16142: testing Filtering $cf_rpath_src ..." 1>&5
             fi
             test -n "$verbose" && echo "	...Filter $cf_rpath_tmp" 1>&6
 
-echo "${as_me-configure}:16153: testing ...Filter $cf_rpath_tmp ..." 1>&5
+echo "${as_me-configure}:16161: testing ...Filter $cf_rpath_tmp ..." 1>&5
 
             EXTRA_LDFLAGS="$cf_rpath_tmp $EXTRA_LDFLAGS"
             ;;
@@ -16162,15 +16170,15 @@ echo "${as_me-configure}:16153: testing ...Filter $cf_rpath_tmp ..." 1>&5
     LDFLAGS=$cf_rpath_dst
     test -n "$verbose" && echo "	...checked LDFLAGS $LDFLAGS" 1>&6
 
-echo "${as_me-configure}:16165: testing ...checked LDFLAGS $LDFLAGS ..." 1>&5
+echo "${as_me-configure}:16173: testing ...checked LDFLAGS $LDFLAGS ..." 1>&5
 
     test -n "$verbose" && echo "	...checked EXTRA_LDFLAGS $EXTRA_LDFLAGS" 1>&6
 
-echo "${as_me-configure}:16169: testing ...checked EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
+echo "${as_me-configure}:16177: testing ...checked EXTRA_LDFLAGS $EXTRA_LDFLAGS ..." 1>&5
 
 fi
 else
-echo "$as_me:16173: result: no" >&5
+echo "$as_me:16181: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -16280,7 +16288,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:16283: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:16291: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -16456,7 +16464,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:16459: error: ambiguous option: $1
+    { { echo "$as_me:16467: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -16475,7 +16483,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:16478: error: unrecognized option: $1
+  -*) { { echo "$as_me:16486: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -16571,7 +16579,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "include/ncurses_cfg.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/ncurses_cfg.h:include/ncurses_cfg.hin" ;;
-  *) { { echo "$as_me:16574: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:16582: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -16953,7 +16961,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:16956: creating $ac_file" >&5
+    { echo "$as_me:16964: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -16971,7 +16979,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:16974: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:16982: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -16984,7 +16992,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:16987: error: cannot find input file: $f" >&5
+           { { echo "$as_me:16995: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -17050,7 +17058,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:17053: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:17061: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -17061,7 +17069,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:17064: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:17072: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -17074,7 +17082,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:17077: error: cannot find input file: $f" >&5
+           { { echo "$as_me:17085: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -17132,7 +17140,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:17135: $ac_file is unchanged" >&5
+      { echo "$as_me:17143: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
