ncurses 5.7 - patch 20100717
* add hard-reset for rs2 to wsvt25 to help ensure that reset ends
  the alternate character set (patch by Nicholas Marriott)
+ remove tar-copy.sh and related configure/Makefile chunks, since the
  Ada95 binding is now installed using rules in Ada95/src.

diff --git a/Ada95/configure b/Ada95/configure
--- a/Ada95/configure
+++ b/Ada95/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.16 .
+# From configure.in Revision: 1.17 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20100530.
 #
@@ -11117,15 +11117,6 @@ TEST_LIBS2=
 
 NCURSES_SHLIB2="sh -c"
 
-for cf_path in . .. ../..
-do
-	if test -f $cf_path/tar-copy.sh
-	then
-		NCURSES_COPY2=`echo 'sh $(top_srcdir)/'$cf_path'/tar-copy.sh' | sed -e 's,/./,/,'`
-		break
-	fi
-done
-
 ADA_SUBDIRS="include gen src samples"
 for cf_dir in $ADA_SUBDIRS
 do
@@ -11217,7 +11208,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:11220: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:11211: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -11393,7 +11384,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:11396: error: ambiguous option: $1
+    { { echo "$as_me:11387: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -11412,7 +11403,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:11415: error: unrecognized option: $1
+  -*) { { echo "$as_me:11406: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -11481,7 +11472,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "include/ncurses_cfg.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/ncurses_cfg.h:include/ncurses_cfg.hin" ;;
-  *) { { echo "$as_me:11484: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:11475: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -11673,7 +11664,6 @@ s,@cross_compiling@,$cross_compiling,;t t
 s,@TEST_ARG2@,$TEST_ARG2,;t t
 s,@TEST_LIBS2@,$TEST_LIBS2,;t t
 s,@NCURSES_SHLIB2@,$NCURSES_SHLIB2,;t t
-s,@NCURSES_COPY2@,$NCURSES_COPY2,;t t
 s,@ADA_SUBDIRS@,$ADA_SUBDIRS,;t t
 s,@NCURSES_TREE@,$NCURSES_TREE,;t t
 s,@EXTERNAL_TREE@,$EXTERNAL_TREE,;t t
@@ -11791,7 +11781,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11794: creating $ac_file" >&5
+    { echo "$as_me:11784: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11809,7 +11799,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11812: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11802: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11822,7 +11812,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11825: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11815: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11888,7 +11878,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11891: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11881: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11899,7 +11889,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11902: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11892: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11912,7 +11902,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11915: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11905: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11970,7 +11960,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11973: $ac_file is unchanged" >&5
+      { echo "$as_me:11963: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.500 .
+# From configure.in Revision: 1.501 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20100530.
 #
@@ -18716,8 +18716,6 @@ done
 # symbols that differ when compiling Ada95 by itself.
 NCURSES_SHLIB2='sh $(top_srcdir)/misc/shlib'
 
-NCURSES_COPY2='sh $(top_srcdir)/tar-copy.sh'
-
 # values to use as strings
 cat >>confdefs.h <<EOF
 #define NCURSES_PATHSEP '$PATH_SEPARATOR'
@@ -18922,7 +18920,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:18925: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:18923: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -19098,7 +19096,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:19101: error: ambiguous option: $1
+    { { echo "$as_me:19099: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -19117,7 +19115,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:19120: error: unrecognized option: $1
+  -*) { { echo "$as_me:19118: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -19219,7 +19217,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "include/ncurses_cfg.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/ncurses_cfg.h:include/ncurses_cfg.hin" ;;
-  *) { { echo "$as_me:19222: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:19220: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -19504,7 +19502,6 @@ s,@TEST_DEP2@,$TEST_DEP2,;t t
 s,@ADA_SUBDIRS@,$ADA_SUBDIRS,;t t
 s,@DIRS_TO_MAKE@,$DIRS_TO_MAKE,;t t
 s,@NCURSES_SHLIB2@,$NCURSES_SHLIB2,;t t
-s,@NCURSES_COPY2@,$NCURSES_COPY2,;t t
 s,@HAVE_TCGETATTR@,$HAVE_TCGETATTR,;t t
 s,@HAVE_TERMIO_H@,$HAVE_TERMIO_H,;t t
 s,@HAVE_TERMIOS_H@,$HAVE_TERMIOS_H,;t t
@@ -19624,7 +19621,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:19627: creating $ac_file" >&5
+    { echo "$as_me:19624: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -19642,7 +19639,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:19645: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:19642: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -19655,7 +19652,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:19658: error: cannot find input file: $f" >&5
+           { { echo "$as_me:19655: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -19721,7 +19718,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:19724: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:19721: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -19732,7 +19729,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:19735: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:19732: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -19745,7 +19742,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:19748: error: cannot find input file: $f" >&5
+           { { echo "$as_me:19745: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -19803,7 +19800,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:19806: $ac_file is unchanged" >&5
+      { echo "$as_me:19803: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
